#
# actions/labeler 用
#
# GitHub
# - https://github.com/actions/labeler
#
# ラベルの重複は許容
#
---

#
# src/main
#
src/main:
  - 'src/main/*'
  - 'src/main/**/*'

#
# test系
#
src/test:
  - 'src/test/*'
  - 'src/test/**/*'

#
# プレゼンテーション層
#
presentation:
  - '**/presentation/*'
  - '**/presentation/**/*'

#
# ユースケース層
#
usecase:
  - '**/usecase/*'
  - '**/usecase/**/*'

#
# ドメイン層
#
domain:
  - '**/domain/*'
  - '**/domain/**/*'

#
# インフラ層
#
infra:
  - '**/infra/*'
  - '**/infra/**/*'

#
# detekt
#
detekt:
  - 'config/detekt/*'
