---

# comments のルール
comments:
  #
  # UndocumentedPublicClass
  #
  # 概要
  # - 説明のないパブリッククラスを禁止する
  #
  UndocumentedPublicClass:
    active: true  # (default: false)
  #
  # UndocumentedPublicClass
  #
  # 概要
  # - 説明のないパブリックな関数を禁止する
  #
  UndocumentedPublicFunction:
    active: true  # (default: false)
  #
  # UndocumentedPublicClass
  #
  # 概要
  # - 説明のないパブリックなプロパティを禁止する
  #
  UndocumentedPublicProperty:
    active: true  # (default: false)

# style のルール
style:
  active: true
  #
  # UnusedImports
  #
  # 概要
  # - 未使用の import を禁止する
  #
  UnusedImports:
    active: true  # (default: false)
