---
# complexityのルール
complexity:
  active: true
  #
  # LongParameterList
  #
  # 概要
  # - コンストラクタの引数の数
  # - 関数の引数の数
  #
  LongParameterList:
    active: true
    functionThreshold: 12  # (default: 6)
    constructorThreshold: 12  # (default: 7)
    ignoreDefaultParameters: false
    ignoreDataClasses: true
    ignoreAnnotatedParameter: []

# comments のルール
comments:
  #
  # UndocumentedPublicClass
  #
  # 概要
  # - 説明のないパブリッククラスを禁止する
  #
  UndocumentedPublicClass:
    active: true  # (default: false)
  #
  # UndocumentedPublicClass
  #
  # 概要
  # - 説明のないパブリックな関数を禁止する
  #
  UndocumentedPublicFunction:
    active: true  # (default: false)
  #
  # UndocumentedPublicClass
  #
  # 概要
  # - 説明のないパブリックなプロパティを禁止する
  #
  UndocumentedPublicProperty:
    active: true  # (default: false)

# style のルール
style:
  active: true
  #
  # UnusedImports
  #
  # 概要
  # - 未使用の import を禁止する
  #
  UnusedImports:
    active: true  # (default: false)
