---
name: Lint Shell

#
# 'on' にしている理由
# yamllintで怒られるため
#
# 参考: https://github.com/adrienverge/yamllint/issues/430
#
'on':
  pull_request:

jobs:
  lint-shell:
    name: Lint Shell
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          path: "."
          pattern: "*.sh"
          exclude: "./.git/*"
          check_all_files_with_shebangs: "false"  # パターンに関係なくシェバンを持つファイルのチェックをするかどうか
