---

name: Lint GitHub Action

#
# 'on' にしている理由
# yamllintで怒られるため
#
# 参考: https://github.com/adrienverge/yamllint/issues/430
#
'on':
  pull_request:

jobs:
  lint-gh-action:
    name: Lint GitHub Action
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3
      - name: actionlint
        uses: reviewdog/action-actionlint@v1
